### PR TITLE
setup-monitors-in-i3-tutorial

### PR DESCRIPTION
**Pull request by rikkarth**
If there's anything specific you would like to see included in this tutorial while working on this PR let me know.

### CODE REVIEW

**Review by leanghok120 — APPROVED** [review]
LGTM

**Comment by rbeene** [comment]
hey @rikkarth  - is this ready for review?

**Comment by rikkarth** [comment]
Hey, I will do my best to have this completed between today and tomorrow.

Sorry but as I said on discord this has been a very busy week for me, and I wanted to make sure everything is in order before I flag this as ready.

Thank you. 🙏

**Comment by rbeene** [comment]
Don't sweat it! I just wanted to make sure I didn't leave it sitting here if it was ready. Take your time. As creators, I get that real life happens :-)

Thank you!

**Comment by rikkarth** [comment]
This tutorial is finalized.

Let me know if there are any adjustments you would like me to make.

Thank you and have a nice day.

**Review by mthomps4 — APPROVED** [review]

**Comment by rikkarth** [comment]
Just want to highlight that I had requested @rbeene a generated image for the banner. Would appreciate if you guys were able to provide one and I can add it.

**Pull request merged**
